#ifndef SB_H
#define SB_H

#define SB_BASE_ADDRESS 	0x220
#define SB_MPU_401_ADDRESS 	0x330

#define SB_MPU_401_DATA		SB_MPU_401_ADDRESS + 0x0
#define SB_MPU_401_STATUS	SB_MPU_401_ADDRESS + 0x1
#define SB_MPU_401_COMMAND	SB_MPU_401_ADDRESS + 0x1

#define SB_MUSIC_STATUS 					SB_BASE_ADDRESS + 0x0
#define SB_MUSIC_REGISTER_ADDRESS 			SB_BASE_ADDRESS + 0x0
#define SB_MUSIC_REGISTER_DATA 				SB_BASE_ADDRESS + 0x1

#define SB_ADV_FM_MUSIC_STATUS 				SB_BASE_ADDRESS + 0x2
#define SB_ADV_FM_MUSIC_ADDRESS 			SB_BASE_ADDRESS + 0x2
#define SB_ADV_FM_MUSIC_DATA				SB_BASE_ADDRESS + 0x3

#define SB_MIXER_ADDRESS				 	SB_BASE_ADDRESS + 0x4
#define SB_MIXER_DATA						SB_BASE_ADDRESS + 0x5

#define SB_DSP_RESET						SB_BASE_ADDRESS + 0x6

#define SB_FM_MUSIC_STATUS 					SB_BASE_ADDRESS + 0x8
#define SB_FM_MUSIC_ADDRESS 				SB_BASE_ADDRESS + 0x8
#define SB_FM_MUSIC_DATA					SB_BASE_ADDRESS + 0x9

#define SB_DSP_READ_DATA					SB_BASE_ADDRESS + 0xA
#define SB_DSP_WRITE_COMMAND				SB_BASE_ADDRESS + 0xC
#define SB_DSP_WRITE_DATA					SB_BASE_ADDRESS + 0xC
#define SB_DSP_WRITE_BUFFER_STATUS			SB_BASE_ADDRESS + 0xC
#define SB_DSP_READ_BUFFER_STATUS			SB_BASE_ADDRESS + 0xE

#define SB_CD_COMMAND						SB_BASE_ADDRESS + 0x10
#define SB_CD_DATA							SB_BASE_ADDRESS + 0x10
#define SB_CD_STATUS						SB_BASE_ADDRESS + 0x11
#define SB_CD_RESET							SB_BASE_ADDRESS + 0x12
#define SB_CD_ENABLE						SB_BASE_ADDRESS + 0x13

#endif